name: Build Package

on:
  push:
    branches:
      - feat/9/python-packaging
  # pull_request:
  #   branches:
  #     - feat/9/python-packaging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install tree CLI tool
      run: sudo apt-get install tree

    - name: Display directory tree before build
      run: tree

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

    - name: Print working directory
      run: pwd

    - name: List files in current directory
      run: ls -la

    - name: Build package
      run: python python-pack-assign/setup.py sdist bdist_wheel
      working-directory: python-pack-assign

    - name: Display directory tree after build
      run: tree

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: python-pack-assign/dist/
