name: CI for Conda Environment

on:
  push:
    branches:
      - feat/7/ci-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          
      - name: Remove existing Conda environment
        run: conda env remove -n myenv || true

      - name: Create Conda environment
        run: conda env create -f env.yml -n myenv

      - name: Activate Conda environment
        run: echo "CONDA_ENV=myenv" >> $GITHUB_ENV

      - name: Verify Conda environment
        run: conda info --envs

      - name: Install flake8
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          conda install -y flake8

      - name: Run flake8
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          flake8 .

      - name: Run nonstandardcode.py
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          python nonstandardcode.py
