name : Deploy Package

on:
  push:
    branches:
      - feat/9/python-packaging

  workflow_run:
    workflows: ["Build Package"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.13

    - name: List files in dist directory
      run: ls -la python-pack-assign/dist/
    - name: List files in current directory
      run: ls -la

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: python-pack-assign/dist/

    - name: Install package
      run: pip install dist/python_pack_assign-0.1-py3-none-any.whl

    - name: Run nonstandardcode.py
      run: python -m your_package.nonstandardcode