name: Deploy Package

on:
  workflow_run:
    workflows: ["Build Package"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.13

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: python-pack-assign/dist/

    - name: Install package
      run: pip install dist/python_package-0.1-py3-none-any.whl

    - name: Run nonstandardcode.py
      run: python -m your_package.nonstandardcode