name : Build and Test - Refactored

on:
  push:
    branches:
      - enh/17/workflow-scripts
  pull_request:
    branches:
      - enh/17/workflow-scripts

jobs:
  unit-test:
    name: Unit Test Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.13

    - name: Install dependencies from env.yml
      run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda env create -f env.yml -n myenv || conda activate myenv
          conda activate myenv

    - name: Activate Conda environment
      run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          conda list

    - name: Install tree
      run: sudo apt-get install tree

    - name: Build package
      run: python setup.py sdist bdist_wheel
      working-directory: python-pack-assign

    - name: Display directory tree after build
      run: tree

    - name: Install package
      run: pip install -e .

    - name: Run unit tests
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate myenv
        export PYTHONPATH=src
        pytest tests/unit_tests/
      working-directory: python-pack-assign
      continue-on-error: false


  build:
    name: build job
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.13

    - name: Create environment and install dependencies from env.yml
      run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda env create -f env.yml -n myenv || conda activate myenv
          conda activate myenv
          conda install -c conda-forge setuptools wheel

    - name: Build package
      run: python setup.py sdist bdist_wheel
      working-directory: python-pack-assign

    - name: Install package
      run: pip install python-pack-assign/dist/python_pack_assign-0.1-py3-none-any.whl

    - name: Run Installation tests
      run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          export PYTHONPATH=src
          pytest tests/test_installation.py
      working-directory: python-pack-assign
      continue-on-error: false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: python-pack-assign/dist/

  deploy:
    name: deploy job
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        # activate-environment: myenv
        # environment-file: ../env.yml
        # auto-activate-base: false
        auto-update-conda: true
        python-version: 3.13

    - run: |
        conda info
        conda list

    - name: Install dependencies from env.yml
      run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda env create -f env.yml -n myenv || conda activate myenv
          conda activate myenv

    - name: Activate Conda environment
      run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate myenv
          conda list

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: python-pack-assign/dist/

    - name: Install package
      run: pip install python-pack-assign/dist/python_pack_assign-0.1-py3-none-any.whl

    - name: Print working directory
      run: |
        pwd

    - name: Set PYTHONPATH to include src directory
      run: |
          export PYTHONPATH=$(pwd):$PYTHONPATH
        # export PYTHONPATH=$(pwd)/python-pack-assign:$PYTHONPATH
        # echo $PYTHONPATH  # Debugging step to ensure PYTHONPATH is correct

    - name: Run Workflow Scripts
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate myenv
        python src/scripts/data_ingest_run.py -h
        python src/scripts/data_ingest_run.py datasets/housing
        python src/scripts/train_run.py -h
        python src/scripts/train_run.py datasets/housing datasets/models
        python src/scripts/score_run.py -h
        python src/scripts/score_run.py datasets/models datasets/housing datasets/output
      working-directory: python-pack-assign/